[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"], default-features = false }
serde_json = { version = "1.0.135", default-features = false, features = ["alloc"] }

